version: '3.7'
networks:
  server-java_eknetwork: # 실제 app 컨테이너 네트워크 이름으로 변경
    external: true
    
services:
  k6:
    image: grafana/k6:latest
    networks:
      - server-java_eknetwork
    volumes:
      - ./k6:/scripts
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    command: run /scripts/test.js
    
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    networks:
      - server-java_eknetwork
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
      
  grafana:
    image: grafana/grafana:9.3.8
    container_name: grafana
    networks:
      - server-java_eknetwork
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana:/etc/grafana/provisioning/